default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: my_file_development

test:
  <<: *default
  database: my_file_test

production:
  <<: *default
  database: my_file_production
